In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [12]:
dataset=pd.read_csv("CKD.csv")

In [13]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [14]:
dataset = dataset.drop(columns=['age'])

In [15]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [16]:
dataset

,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,38.868902,...,False,False,False,False,False,False,True,True,False,True
1,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,34.000000,...,True,False,False,False,False,False,True,False,False,True
2,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,34.000000,...,True,False,False,False,False,False,True,False,False,True
3,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,38.868902,...,True,False,False,False,False,False,True,False,True,True
4,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,36.000000,...,True,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,37.000000,...,True,False,False,False,False,False,True,False,False,True
395,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,27.000000,...,True,False,False,True,True,False,True,False,True,True
396,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,26.000000,...,True,False,False,True,True,False,False,False,False,True
397,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,38.868902,...,True,False,False,True,True,False,True,False,True,True
398,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,53.000000,...,True,False,False,False,False,False,True,False,False,False

In [17]:
x=dataset[['bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc',
       'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
y=dataset[['classification_yes']]

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=11)

In [19]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(random_state=0, n_estimators=100,criterion='entropy')
classifier.fit(x, y)

C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier(criterion='entropy', random_state=0)

In [29]:
y_pred=classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[22  0]
 [ 0 58]]

In [30]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(clf_report)

              precision    recall  f1-score   support

       False       1.00      1.00      1.00        22
        True       1.00      1.00      1.00        58

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80

In [31]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y, classifier.predict_proba(x)[:, 1])

1.0

In [32]:
from sklearn.metrics import precision_score
precision=precision_score(y_test,y_pred,average='weighted')
precision

1.0

In [33]:
from sklearn.metrics import f1_score
f1_score(y_test,y_pred,average='weighted')

1.0

In [34]:
from sklearn.metrics import recall_score
recall_score(y_test,y_pred,average='weighted')

1.0